# Numpy연습문제

* version:2021.6.11

#### Q:1-1
`np` 라는 이름으로 numpy를 import하시오

In [1]:
import 

#### Q:1-2
값이 0이고 사이즈 10의 배열(numpy.ndarray)를 작성하시오(a1_2)  
(hint: np.zeros)

【참고】 
Numpy입문.ipynb#0-배열 만들기  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html

In [2]:

a1_2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Q:1-3
값이 0이고 10x10의 배열을 작성하고(a1_3) 메모리 사이즈를 확인(b1_3)하시오

【참고】 https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.nbytes.html

In [3]:

print(b1_3)

800


#### Q:1-4
갑이 0이고 사이즈가 10인 배열을 만들고(a1_4)、다섯번째 값을 1을 넣으시오

【참고】 Numpy입문.ipynb #index 지정

In [4]:


a1_4

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### Q:1-5
10부터 49까지의 정수로 이루어진 배열(a1_5)을 작성하시오  
(hint: np.arange)

【참고】 https://docs.scipy.org/doc/numpy-1.16.0/reference/generated/numpy.arange.html

In [5]:

a1_5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Q:1-6
Q:1-5 에서 작성한 배열의 역순의 배열을 작성하시오(a1_6)

【참고】 
Numpy입문.ipynb #index 범위로 호출
https://docs.scipy.org/doc/numpy-1.16.0/reference/arrays.indexing.html#basic-slicing-and-indexing

In [6]:

a1_6

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### Q:1-7
0부터 8까지의 배열을 작성하고 3×3의 행렬로 변환하시오(a1_7)  
(hint: reshape)

【참고】 
Numpy입문.ipynb#shape 변경
https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html

In [7]:

a1_7

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Q:1-8
\[1,2,0,0,4,0\] 배열(a1_8)에서 0 이외의 요소의 index를 작성하시오(b1_8)  
(hint: np.nonzero)

【참고】 
Numpy입문.ipynb#0이 아닌 요소의 index를 반환
https://docs.scipy.org/doc/numpy/reference/generated/numpy.nonzero.html

In [8]:
a1_8 = np.array([1,2,0,0,4,0])

b1_8

(array([0, 1, 4], dtype=int64),)

#### Q:1-9
3☓3 형태의 단위행렬을 작성하시오(a1_9)   
(hint: np.eye)

【참고】 
Numpy입문.ipynb#단위행렬 만들기
https://docs.scipy.org/doc/numpy/reference/generated/numpy.eye.html

In [9]:

a1_9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Q:1-10
3☓3☓3 행렬을 난수로 작성하시오(a1_10)  
(hint: np.random.random)

【참고】 https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.random.html

In [10]:
np.random.seed(1)
a1_10

array([[[4.17022005e-01, 7.20324493e-01, 1.14374817e-04],
        [3.02332573e-01, 1.46755891e-01, 9.23385948e-02],
        [1.86260211e-01, 3.45560727e-01, 3.96767474e-01]],

       [[5.38816734e-01, 4.19194514e-01, 6.85219500e-01],
        [2.04452250e-01, 8.78117436e-01, 2.73875932e-02],
        [6.70467510e-01, 4.17304802e-01, 5.58689828e-01]],

       [[1.40386939e-01, 1.98101489e-01, 8.00744569e-01],
        [9.68261576e-01, 3.13424178e-01, 6.92322616e-01],
        [8.76389152e-01, 8.94606664e-01, 8.50442114e-02]]])

#### Q:1-11
10☓10 행렬을 난수로 작성하고 최대치(a1_11_max)와 최소치(a1_11_min)를 표시하시오  
(hint: min, max)


【참고】 
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.max.html  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.min.html

In [11]:
np.random.seed(1)

print(a1_11_min, a1_11_max)

0.00011437481734488664 0.9888610889064947


#### Q:1-12
사이즈가 30인 배열을 난수로 작성하고(a1_12) 그 값들의 평균을 구하시오(a1_12_mean)  
(hint: mean)

【참고】 https://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html

In [12]:
np.random.seed(1)

print(a1_12_mean)

0.43544785374154765


#### Q:1-13
10☓10 크기의 값이 1인 행렬을 작성하고(a1_13) 안쪽을 0으로 채우시오  
(hint: array[1:-1, 1:-1])

【참고】 
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html  
https://docs.scipy.org/doc/numpy-1.16.0/user/basics.indexing.html

In [13]:

a1_13

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### Q:1-14
10☓10 크기의 값이 1인 행렬을 작성하고 테두리를 0으로 채우시오 
(hint: np.pad)

【참고】 https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.pad.html

In [14]:

a1_14

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### Q:1-15
아래의 연산의 결과를 확인하시오
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

nan

False

False

nan

False

#### Q:1-16
아래와 같은 행렬(numpy.ndarray)을 작성하시오(a1_16)
```
    [[0 0 0 0 0]  
     [1 0 0 0 0]  
     [0 2 0 0 0]  
     [0 0 3 0 0]  
     [0 0 0 4 0]]
 ```
 (hint: np.diag)
 
  【참고】 https://docs.scipy.org/doc/numpy/reference/generated/numpy.diag.html

In [20]:

a1_16

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### Q:1-17
아래와 같은 행렬(numpy.ndarray)을 작성하시오(a1_17)
 ```
     [[0 1 0 1 0 1 0 1]
     [1 0 1 0 1 0 1 0]
     [0 1 0 1 0 1 0 1]
     [1 0 1 0 1 0 1 0]
     [0 1 0 1 0 1 0 1]
     [1 0 1 0 1 0 1 0]
     [0 1 0 1 0 1 0 1]
     [1 0 1 0 1 0 1 0]]
```
(hint: array[::2])

【참고】 
https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html  
https://docs.scipy.org/doc/numpy-1.16.0/user/basics.indexing.html

In [21]:

a1_17

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### Q:1-18
6x7x8 행렬에서 100번째 요소의 index를 확인하시오(a1_18)  
(hint: np.unravel_index)

【참고】 https://docs.scipy.org/doc/numpy/reference/generated/numpy.unravel_index.html

In [22]:

a1_18

(1, 5, 4)

#### Q:1-19
tile 함수를 사용하여 `Q:1-17`의 행렬을 작성하시오(a1_19)

【참고】 https://docs.scipy.org/doc/numpy/reference/generated/numpy.tile.html

In [23]:

a1_19

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### Q:1-20
5x5 행렬을 난수로 작성하고(a1_20) 정규화(최대값을 1, 최소값을 0) 하시오(b1_20)  

【참고】 
https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.random.html
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.max.html  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.min.html

In [24]:
np.random.seed(1)
a1_20 = 

print(b1_20)

[[0.43062422 0.74390559 0.         0.31216141 0.15146614]
 [0.09525847 0.19227018 0.35681181 0.4097033  0.55642609]
 [0.4328682  0.70764562 0.21106075 0.90689005 0.02817053]
 [0.69240828 0.43091632 0.57695302 0.14488764 0.20450104]
 [0.82697155 1.         0.32361794 0.71498243 0.9051049 ]]


#### Q:1-21
텍스트 파일을 데이터 타입이 `np.int`로 배열에 읽어들이시오(a1_21)  
(hint: np.genfromtxt)

【참고】 
https://docs.scipy.org/doc/numpy/reference/generated/numpy.genfromtxt.html

In [25]:
from io import StringIO

text = """1, 2, 3, 4, 5\n
    6,  ,  , 7, 8\n
    ,  , 9,10,11\n"""
file = StringIO(text)
a1_21 = 
print(a1_21)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### Q:1-22
값 1의 5x3 행렬에 값 1의 3x2 행렬을 곱하시오(a1_22)  
(hint: np.dot | @)

【참고】 
Numpy입문.ipynb #곱셈  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html  

In [26]:

a1_22

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### Q:1-23
0부터 10까지의 배열을 작성하고(a1_23) 4부터 8까지의 값을 음수로 하시오  
(hint: >, <=)

In [27]:

a1_23

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

#### Q:1-24
아래와 같은 연산의 결과를 확인하시오
```
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

<ipython-input-28-3585dcb7ab9b>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)


nan

<ipython-input-29-4764261090d0>:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

array([-2.14748365e+09])

#### Q:1-25
float 배열(a1_25)을 올림처리 하시오(b1_25)
```
Z = np.random.uniform(-10, +10, 10)
```
※ 절대값이 큰 쪽으로 만든다(예: -0.7 는 -1, 0.7 은 1)  
(hint: np.uniform, np.copysign, np.ceil, np.abs)

【참고】 
https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.uniform.html  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.copysign.html  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ceil.html   
https://docs.scipy.org/doc/numpy/reference/generated/numpy.absolute.html

In [31]:
np.random.seed(1)
a1_25 = np.random.uniform(-10, +10, 10)
print(a1_25)
b1_25 = 
print(b1_25)

[-1.65955991  4.40648987 -9.9977125  -3.95334855 -7.06488218 -8.1532281
 -6.27479577 -3.08878546 -2.06465052  0.77633468]
[ -2.   5. -10.  -4.  -8.  -9.  -7.  -4.  -3.   1.]


#### Q:1-26
사이즈가 10이고 0부터 10까지의 난수(정수)를 두개 만들고(a1_26, b1_26) 그 공통 값을 출력하시오(c1_26)  
(hint: np.intersect1d)

【참고】 
https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.randint.html  
https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.intersect1d.html

In [32]:
np.random.seed(1)


print(c1_26)

[5 7 9]


#### Q:1-27
아래와 같은 연산의 결과를 확인하시오
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

<ipython-input-33-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### Q:1-28
numpy.datetime64 를 이용하여 어제(yesterday), 오늘(today) 내일(tomorrow)의 날짜를 각각의 변수에 저장하시오  
(hint: np.datetime64, np.timedelta64)

【참고】 https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.datetime.html

In [34]:
yesterday = 
today = 
tomorrow = 

#### Q:1-29
2016년 7월의 모든 날짜를 넣은 배열을 만드시오(a1_29)  
(hint: np.arange(dtype='datetime64[D]'))

【참고】 
https://docs.scipy.org/doc/numpy-1.16.0/reference/generated/numpy.arange.html  
https://docs.scipy.org/doc/numpy-1.16.0/reference/generated/numpy.dtype.html#numpy.dtype

In [35]:

a1_29

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### Q:1-30
((A + B) \* (-A / 2)) 를 계산하시오
```
A = np.ones(3) * 1
B = np.ones(3) * 2
```
(hint: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [36]:
A = np.ones(3) * 1
B = np.ones(3) * 2




array([-1.5, -1.5, -1.5])

#### Q:1-31
다섯개의 각각 다른 함수나 메서드를 사용하여 랜덤 배열(a1_31) 정수부분을 추출하시오
```
Z = np.random.uniform(0, 10, 10)
```
(hint: %, np.floor, np.ceil, astype, np.trunc)

【참고】 
https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.floor.html  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ceil.html  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.astype.html  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.trunc.html  
https://docs.python.org/ja/3/reference/expressions.html#binary-arithmetic-operations

In [37]:
np.random.seed(1)
a1_31 = np.random.uniform(0, 10, 10)

array([4., 7., 0., 3., 1., 0., 1., 3., 3., 5.])

array([4., 7., 0., 3., 1., 0., 1., 3., 3., 5.])

array([4., 7., 0., 3., 1., 0., 1., 3., 3., 5.])

array([4, 7, 0, 3, 1, 0, 1, 3, 3, 5])

array([4., 7., 0., 3., 1., 0., 1., 3., 3., 5.])

#### Q:1-32
행의 값이 0부터 4까지인 5x5인 행렬을 만드시오(a1_32)  
(hint: np.arange)

【참고】 https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html

In [43]:

a1_32

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### Q:1-33
0부터 1까지의 10개의 등차수열을 작성하시오(a1_33)(0과 1은 미포함)  
(hint: np.linspace)

【참고】 https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html

In [44]:

a1_33

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### Q:1-34
랜덤한 값을 갖는 사이즈 10의 배열을 작성하여 정렬하시오(a1_34)

【참고】 https://docs.scipy.org/doc/numpy/reference/generated/numpy.sort.html

In [45]:
np.random.seed(1)

a1_34

array([1.14374817e-04, 9.23385948e-02, 1.46755891e-01, 1.86260211e-01,
       3.02332573e-01, 3.45560727e-01, 3.96767474e-01, 4.17022005e-01,
       5.38816734e-01, 7.20324493e-01])

#### Q:1-35
배열(a1_35)을 이뮤터블(읽기전용)로 만드시오  
(hint: flags.writeable)

【참고】 https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.flags.html

In [46]:
a1_35 = np.zeros(10)


a1_35[0] = 1

ValueError: assignment destination is read-only

#### Q:1-36
랜덤한 값을 갖고 사이즈가 10인 배열을 만들고 최대치를 0으로 하시오(a1_36)  
(hint: argmax)

【참고】 https://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html

In [47]:
np.random.seed(1)

a1_36

array([4.17022005e-01, 0.00000000e+00, 1.14374817e-04, 3.02332573e-01,
       1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01,
       3.96767474e-01, 5.38816734e-01])

#### Q:1-37
모든 numpy 스칼라 데이터 타입들의 최소값과 최대값을 반환하는 함수 `f1_37`를 만드시오  
(hint: np.iinfo, np.finfo)

【참고】 
https://docs.scipy.org/doc/numpy/reference/generated/numpy.iinfo.html  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.finfo.html

In [48]:
def f1_37(dtype):
    """
    Parameters
    ----------
    dtype : np.dtype
           데이터 타입
    Return
    ----------
    min
        최소값
    max
        최대값
    """
    dtype_list = [np.int8, np.int16, np.int32, np.int64, np.float16, np.float32, np.float64]
    
    return 


print(f1_37(np.int8))
print(f1_37(np.int16))
print(f1_37(np.int32))
print(f1_37(np.int64))
print(f1_37(np.float16))
print(f1_37(np.float32))
print(f1_37(np.float64))

(-128, 127)
(-32768, 32767)
(-2147483648, 2147483647)
(-9223372036854775808, 9223372036854775807)
(-65500.0, 65500.0)
(-3.4028235e+38, 3.4028235e+38)
(-1.7976931348623157e+308, 1.7976931348623157e+308)


#### Q:1-38
난수 `np.random.uniform(0, 1, 10)`로 작성한 배열(a1_38)에서 0.5에 가장 가까운 값을 추출하시오(b1_38)  
(hint: np.abs, argmin, flat)

【참고】 
https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.ndarray.flat.html  
https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.absolute.html  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.argmin.html

In [49]:
np.random.seed(1)
a1_38 = 
b1_38 = 
print(b1_38)

0.538816734003357


#### Q:1-39
0부터 10까지의 float (32 bits)의 배열을 int(32 bits)로 변환하시오(a1_39)  
(hint: astype(copy=False))

【참고】 https://docs.scipy.org/doc/numpy-1.16.0/reference/generated/numpy.ndarray.astype.html

In [50]:
a1_39

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Q:1-40
행렬(a1_40)의 모든 요서에 대해 각 행의 평균값을 빼시오(b1_40)
```python
a1_40 = np.random.rand(5, 10)
```
(hint: mean(axis=,keepdims=))

【참고】 https://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html

In [51]:
np.random.seed(1)
a1_40 = np.random.rand(5, 10)

b1_40 = 
b1_40

array([[ 0.1023927 ,  0.40569519, -0.31451493, -0.01229674, -0.16787342,
        -0.22229071, -0.1283691 ,  0.03093142,  0.08213817,  0.22418743],
       [-0.00073767,  0.26528731, -0.21547994,  0.45818525, -0.39254459,
         0.25053532, -0.00262738,  0.13875764, -0.27954525, -0.2218307 ],
       [ 0.2289625 ,  0.39647951, -0.25835789,  0.12054055,  0.30460709,
         0.3228246 , -0.48673786, -0.53272728, -0.40195165,  0.30636044],
       [-0.43239929, -0.1096385 ,  0.42714341,  0.00241916,  0.16113099,
        -0.21523049,  0.15575481,  0.30387955, -0.51245784,  0.21939819],
       [ 0.49107277,  0.25037734, -0.21734432,  0.29149101, -0.39456231,
        -0.04989479,  0.41080719, -0.20417417, -0.21001298, -0.36775974]])

#### Q:1-41
2차원 배열에 빈 열이 있는 경우는 True, 없는 경우는 False를 반환하는 함수(f1_41)를 만드시오  
(hint: any, ~)

【참고】 https://docs.scipy.org/doc/numpy/reference/generated/numpy.any.html

In [52]:
def f1_41(data):
    """
    빈 열이 있는지 아닌지 판단하는 메서드
    Parameters
    -----------
    data : np.ndarray
        numpy의 2차원행렬
    
    Return
    -----------
    bool
        True : 빈 열이 있음
        False : 빈 열이 없음
    """
    
    return 
    

a1_41 = np.array([[0, 1, 0], [1, 0, 0], [1, 0, 0]])
b1_41 = np.array([[0, 1, 0], [0, 0, 0], [1, 0, 1]])

print(a1_41)
print(f1_41(a1_41))
print(b1_41)
print(f1_41(b1_41))

[[0 1 0]
 [1 0 0]
 [1 0 0]]
True
[[0 1 0]
 [0 0 0]
 [1 0 1]]
False
