# Numpy입문

NumPy의 주된 목적은 동차원, 다차원 배열을 간편하게 다루기 위함이다. 이는 양의 정수의 튜플형태로로 인덱스된 같은 타입의 요소 (수치) 테이블이다. NumPy의 차원은 축(軸)이라고 불린다. 축의 수는 랭크이다.

NumPy의 배열클래스는 ndarray라고 불린다 (표준Python라이브러리 클래스 array.array와는 다르다)

## 라이브러리를 호출

In [94]:
!pip install numpy

In [95]:
import numpy as np

## 배열을 확인

In [96]:
arr = np.arange(15).reshape(3, 5)

In [97]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

#### 배열의 축의 개수 (차원수)를 표시

In [98]:
arr.ndim

2

#### 배열의 크기를 표시 (각 차원의 배열 크기를 표시하는 정수의 조합으로 표현한다)

In [99]:
arr.shape

(3, 5)

#### 배열의 요소수의 합계

In [100]:
arr.size

15

#### 배열 내의 객체 타입

In [101]:
arr.dtype

dtype('int32')

#### 배열의 각 요소의 바이트사이즈

In [102]:
arr.itemsize

4

## 배열 만들기
- numpy 배열은 Python 의 리스트 또는 튜플로 작성 가능하다.
- 배열의 타입은 사용한 시퀀스의 요소로부터 결정된다.

#### 1차원 배열

In [103]:
np.array([2, 3, 4])

array([2, 3, 4])

#### 다차원 배열 작성

In [104]:
np.array([(1.5, 2, 3), (4, 5, 6)])

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

#### 복소수 배열

In [105]:
np.array([[1, 2], [3, 4]], dtype=complex)

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

#### 0 의 배열

In [106]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### 1의 배열

In [108]:
np.ones((3, 4), dtype=np.int16)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

#### 단위행렬

In [110]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [111]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [114]:
np.eye(3, dtype=int, k=1)

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

eye 함수는 열수・행수를 지정되는것 이외에도 사선의 위치를 변경하는것도 가능하다.

#### 빈 배열 작성

In [115]:
np.empty((2, 3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

#### 시퀀셜한 배열

In [118]:
np.arange(10, 30, 5)  # 10부터30까지 스텝

array([10, 15, 20, 25])

## 기본적인 연산

### 1차원 배열

In [119]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)

In [120]:
a

array([20, 30, 40, 50])

In [121]:
b

array([0, 1, 2, 3])

#### 덧셈

In [122]:
a + b

array([20, 31, 42, 53])

#### 뺄셈

In [123]:
a - b

array([20, 29, 38, 47])

#### 정수곱셈

In [124]:
b * 2

array([0, 2, 4, 6])

#### 승수(乗数)

In [126]:
b ** 2

array([0, 1, 4, 9], dtype=int32)

#### 비교

In [24]:
a = np.array([20, 30, 40, 50])

In [127]:
a

array([20, 30, 40, 50])

In [128]:
a < 35

array([ True,  True, False, False])

### 2차원 배열

In [129]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])

In [130]:
A

array([[1, 1],
       [0, 1]])

In [132]:
B

array([[2, 0],
       [3, 4]])

#### 배열의 요소간 곱셈

In [134]:
A * B

array([[2, 0],
       [0, 4]])

In [27]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [135]:
np.dot(A, B)

array([[5, 4],
       [3, 4]])

#### 요소의 합

In [136]:
a = np.array([1, 2, 3, 4, 5])
a.sum()

15

#### 요소의 최소값

In [137]:
a = np.array([1, 2, 3, 4, 5])
a.min()

1

#### 요소의 최대값

In [138]:
a = np.array([1, 2, 3, 4, 5])
a.max()

5

#### 축별 요소 합계

In [139]:
a = np.arange(12).reshape(3, 4)

In [144]:
a.sum(axis=1)

array([ 6, 22, 38])

#### 축별 요소의 최소값

In [146]:
a = np.arange(12).reshape(3, 4)
a.min(axis=1)

array([0, 4, 8])

#### 축별 요소의 최대값

In [147]:
a = np.arange(12).reshape(3, 4)
a.max(axis=1)

array([ 3,  7, 11])

#### 축별 요소의 누적합

In [149]:
a = np.arange(12).reshape(3, 4)
print(a)
a.cumsum(axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

## 표준함수

#### 지수함수

In [150]:
A = np.arange(3)

In [150]:
np.exp(A)

array([1.        , 2.71828183, 7.3890561 ])

#### 제곱근

In [152]:
A = np.arange(3)
np.sqrt(A)

array([0.        , 1.        , 1.41421356])

#### sin 함수

In [153]:
A = np.arange(3)
np.sin(A)

array([0.        , 0.84147098, 0.90929743])

#### cos 함수

In [154]:
A = np.arange(3)
np.cos(A)

array([ 1.        ,  0.54030231, -0.41614684])

## index 지정

### 1차원 배열

#### index로 호출

In [155]:
a = np.arange(10) ** 3

In [40]:
a[2]

8

#### index 범위로 호출

In [41]:
a = np.arange(10) ** 3

In [41]:
a[2:5]  # a[5] 는 들어가지 않으므로 주의

array([ 8, 27, 64], dtype=int32)

#### index의 범위로 대입

In [158]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [159]:
a = np.arange(10) ** 3
a[:6:2] = -1000  # 0부터6까지 2스텝으로 원소에 대해 -1000을 대입
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

#### 역순으로 표시

In [160]:
a = np.arange(10) ** 3
a[::-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0], dtype=int32)

### 2차원 배열

In [161]:
def f(x, y):
    return 10 * x + y


a = np.fromfunction(f, (2, 2), dtype=int)
a

array([[ 0,  1],
       [10, 11]])

#### index만으로 호출

In [163]:
a[1, 1]

11

#### index 범위로 호출

In [164]:
a[0:5, 1]

array([ 1, 11])

In [165]:
a[:, 1]  # :은 전부 지정하는 것

array([ 1, 11])

In [166]:
a[1:3, :]

array([[10, 11]])

In [167]:
a[-1]  # 마지막 행을 역순으로 취득한다

array([10, 11])

In [168]:
a[1, ...]  # a[1, :] 와 같다

array([10, 11])

In [169]:
a[..., 0]  # a[:, 2] 와 같다

array([ 0, 10])

## 이터레이션

In [171]:
def f(x, y):
    return 10 * x + y


a = np.fromfunction(f, (5, 4), dtype=int)
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

#### 행마다 반복

In [172]:
for row in a:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


#### index마다 반복

In [174]:
for element in a.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


## 변형

In [175]:
10 * np.random.random((3, 4))

array([[2.84498841, 6.55206864, 5.81538459, 6.47173971],
       [4.45887446, 0.18252534, 5.05583076, 0.28863522],
       [7.64271525, 7.89208248, 6.42505301, 2.76253921]])

In [179]:
tmp = 10 * np.random.random((3, 4))
print(tmp)
a = np.floor(tmp)
print(a)

[[4.29275634 3.68942232 9.46587841 4.96160718]
 [4.7819513  0.82697939 4.51001152 1.18809404]
 [6.01545591 2.0111842  7.71632441 8.22013163]]
[[4. 3. 9. 4.]
 [4. 0. 4. 1.]
 [6. 2. 7. 8.]]


#### 1차원 배열화

In [180]:
a

array([[4., 3., 9., 4.],
       [4., 0., 4., 1.],
       [6., 2., 7., 8.]])

In [181]:
a.ravel()

array([4., 3., 9., 4., 4., 0., 4., 1., 6., 2., 7., 8.])

#### shape 변경

In [182]:
a.reshape(6, 2)

array([[4., 3.],
       [9., 4.],
       [4., 0.],
       [4., 1.],
       [6., 2.],
       [7., 8.]])

In [185]:
a.reshape(3, -1)  # -1 을 대입하면 원래의 형태로부터 자동으로 축의 개수를 정한다

array([[4., 3., 9., 4.],
       [4., 0., 4., 1.],
       [6., 2., 7., 8.]])

In [187]:
b = np.floor(10 * np.random.random((3, 4)))
print(b)
b.resize(6, 2)  # resize 은 reshape 파격적으로 변경을 한다
b

[[3. 3. 0. 4.]
 [2. 4. 9. 6.]
 [0. 0. 3. 1.]]


array([[3., 3.],
       [0., 4.],
       [2., 4.],
       [9., 6.],
       [0., 0.],
       [3., 1.]])

#### 뒤집기

In [188]:
a

array([[4., 3., 9., 4.],
       [4., 0., 4., 1.],
       [6., 2., 7., 8.]])

In [189]:
a.T

array([[4., 4., 6.],
       [3., 0., 2.],
       [9., 4., 7.],
       [4., 1., 8.]])

## Stack

In [190]:
a = np.floor(10 * np.random.random((2, 2)))
b = np.floor(10 * np.random.random((2, 2)))
print(a)
print(b)

[[4. 8.]
 [4. 4.]]
[[0. 7.]
 [7. 2.]]


#### 두개의 배열을 세로로 결합

In [191]:
np.vstack((a, b))

array([[4., 8.],
       [4., 4.],
       [0., 7.],
       [7., 2.]])

#### 두개의 배열을 가로로 결합

In [192]:
np.hstack((a, b))

array([[4., 8., 0., 7.],
       [4., 4., 7., 2.]])

#### 결합

In [198]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [199]:
np.concatenate((a.T, b.T), axis=1)

array([[1, 3, 5],
       [2, 4, 6]])

In [201]:
np.concatenate((a.ravel(), b.ravel()), axis=None)

array([1, 2, 3, 4, 5, 6])

#### 요소 생성

In [202]:
np.r_[1:4, 0, 4]  # 1〜3까지의 값을 넣은 이후에 0, 4를 추가

array([1, 2, 3, 0, 4])

### Split

#### 배열을 열로 n분할

In [203]:
a = np.floor(10 * np.random.random((2, 12)))
print(a)

[[0. 2. 3. 5. 4. 1. 8. 3. 9. 6. 2. 2.]
 [0. 6. 9. 3. 3. 7. 7. 9. 7. 8. 4. 2.]]


In [204]:
np.hsplit(a, 3)  # 열을 n분할

[array([[0., 2., 3., 5.],
        [0., 6., 9., 3.]]),
 array([[4., 1., 8., 3.],
        [3., 7., 7., 9.]]),
 array([[9., 6., 2., 2.],
        [7., 8., 4., 2.]])]

In [69]:
a = np.floor(10 * np.random.random((2, 12)))
print(a)

np.hsplit(a, (3, 4))  # 세번째 열과 네번째 열로 분할

[[4. 8. 1. 0. 7. 3. 7. 2. 5. 3. 3. 3.]
 [9. 9. 8. 7. 2. 6. 8. 5. 7. 6. 2. 4.]]


[array([[4., 8., 1.],
        [9., 9., 8.]]),
 array([[0.],
        [7.]]),
 array([[7., 3., 7., 2., 5., 3., 3., 3.],
        [2., 6., 8., 5., 7., 6., 2., 4.]])]

#### 행렬을 행으로 n분할

In [205]:
a = np.floor(10 * np.random.random((12, 2)))
print(a)

np.vsplit(a, 3)  # 행을 3으로 분할

[[2. 4.]
 [5. 5.]
 [6. 8.]
 [3. 6.]
 [5. 5.]
 [1. 0.]
 [5. 1.]
 [6. 4.]
 [3. 4.]
 [3. 5.]
 [3. 4.]
 [3. 3.]]


[array([[2., 4.],
        [5., 5.],
        [6., 8.],
        [3., 6.]]),
 array([[5., 5.],
        [1., 0.],
        [5., 1.],
        [6., 4.]]),
 array([[3., 4.],
        [3., 5.],
        [3., 4.],
        [3., 3.]])]

In [206]:
a = np.floor(10 * np.random.random((12, 2)))
print(a)

np.vsplit(a, (3, 4))  #  3번째 행과 네번째 행으로 분할

[[0. 5.]
 [1. 7.]
 [5. 6.]
 [1. 4.]
 [7. 9.]
 [9. 6.]
 [8. 4.]
 [9. 3.]
 [7. 6.]
 [5. 6.]
 [1. 3.]
 [2. 3.]]


[array([[0., 5.],
        [1., 7.],
        [5., 6.]]),
 array([[1., 4.]]),
 array([[7., 9.],
        [9., 6.],
        [8., 4.],
        [9., 3.],
        [7., 6.],
        [5., 6.],
        [1., 3.],
        [2., 3.]])]

## 복사

#### No Copy at All

In [213]:
a = np.arange(12)

In [214]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [215]:
b = a

b[-1] = 1000  # 참조 복사이므로 b의 값을 변경하면

a  # a의 값도 변경된다

array([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
       1000])

#### Shallow Copy

In [218]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [219]:
b = a.view()  # Shallow Copy (View copy)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [220]:
b[-1] = 1000  # 참조되는 곳이 같으므로 b의값을 변경하면

a  # a의 값도 변경된다

array([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
       1000])

slice 메서드（a[:]）를 사용하면 view가 반환되므로 주의

#### Deep Copy

In [221]:
a = np.arange(12)
b = a.copy()  # Deep Copy

b[-1] = 1000  # 딥카피 이므로 b의 값을 변경해도

a  # a의 값은 변경되지 않는다

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## 변환

#### 형변환

In [75]:
a = np.arange(0, 5, 0.5)
a.astype(int)

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])

## 논리연산

#### 모든 요소의 진위 판별

In [76]:
a = np.eye(2)
np.all(a > 0)

False

#### 일부 요소의 진위 판별

In [77]:
a = np.eye(2)
np.any(a > 0)

True

#### 0이 아닌 요소의 index를 반환

In [78]:
a = np.eye(3)
np.nonzero(a)

(array([0, 1, 2], dtype=int64), array([0, 1, 2], dtype=int64))

## Ordering

#### 최대값의 index를 반환

In [79]:
a = np.array([1, 4, 5, 3, 2])
np.argmax(a)

2

In [80]:
a = np.array([[1, 3, 4, 2], [2, 4, 1, 3]])
np.argmax(a, axis=0)  # axis를 지정하여 축별로 검색

array([1, 1, 0, 1], dtype=int64)

#### 최소값의 index를 반환

In [81]:
a = np.array([1, 4, 5, 3, 2])
np.argmin(a)

0

In [82]:
a = np.array([[1, 3, 4, 2], [2, 4, 1, 3]])
np.argmin(a, axis=0)  # axis를 지정하여 축별로 검색

array([0, 0, 1, 0], dtype=int64)

#### 요소를 정렬하기 전의 인덱스를 반환

In [83]:
a = np.array([1, 4, 3, 3, 2])

In [84]:
s = a.argsort()

In [85]:
s

array([0, 4, 2, 3, 1], dtype=int64)

In [86]:
a[s]

array([1, 2, 3, 3, 4])

In [87]:
a = np.array([[1, 3, 4, 2], [2, 4, 1, 3]])
np.argsort(a, axis=0)  # axis 를 지정하여 축별로 정렬

array([[0, 0, 1, 0],
       [1, 1, 0, 1]], dtype=int64)

#### 요소를 정렬

In [88]:
a = np.array([1, 4, 5, 3, 2])
np.sort(a)

array([1, 2, 3, 4, 5])

In [89]:
a = np.array([[1, 3, 4, 2], [2, 4, 1, 3]])
np.sort(a, axis=0)  # axis 를 지ㅏ정하여 축별로 정렬

array([[1, 3, 1, 2],
       [2, 4, 4, 3]])

## Statistics

#### 공분산

In [90]:
a = np.array([[0, 2], [1, 1], [2, 0]]).T
print(a)

np.cov(a)

[[0 1 2]
 [2 1 0]]


array([[ 1., -1.],
       [-1.,  1.]])

#### 평균

In [91]:
a = np.array([[1, 2], [3, 4]])
a.mean()

2.5

#### 표준편차

In [92]:
a = np.random.rand(10)
print(a)

np.std(a)

[0.5998568  0.81116384 0.79009753 0.38460479 0.50883437 0.74075008
 0.18283709 0.21230764 0.95595367 0.95142428]


0.26979189994998576

#### 분산

In [93]:
a = np.random.rand(10)
print(a)

np.var(a)

[0.29501268 0.66107326 0.70381008 0.54249937 0.19077534 0.23922789
 0.5742661  0.38331125 0.85757834 0.27347027]


0.04654581021395669